language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: OGGA8hPQzM4QiPUUazwxeeGxMxvztYXR1N+gvk2EhQDVcXARmur3RMVpMD4KwOEoKLCtCWs4ywOejClTZG8emhvkL0MoEDm+ECMRBDfThbfrv28et77Gmt7HJ+l7UflPYL7imt14He+IynIzAo4aGe7lY3WEGAJBCzzHA5ZToo6bWIoAVumiV0S50lcBKFnqAy44Tw+zEzEjBqoxNDLuRI3T3wfzPZItWEHg5ytbLO8op+H/7dcc3Ynx8ggp5ttC0HDAhMdZGtZLi2nhwi1H4QicF1VTsluPkGQOur0iCc/ZfKd1m2wv4b8sVb0XvOKV/gLTx4UVHH4+B/rVcQoOAbFnJFnpQrbtNh34Xul5PiILxsUzWyko2UDatbkVescWSLOGv/yGXu4B/A3vYFdCCFdZNbUubgABFUf+o5nRiaqQ+T/pZ49cdkc+/7+YIdLBxgVFggn/8zEreq7iG3gHW2c+qlSGfaRTjEtEgrJQnEmIiwEVHj8z3JIk0KBLVeRdzoYwEzxD+e5cNp3wPZDtfydcc/URD/TRaTB3RPojyB3aAlMoAcbPtJbcOGREhhM190OjLU9+5IScjuxvwAjKZz6ICvJSnnz2ePqkix8IubzHP9XVuGw8fvg6LYzNCGRTJAqUgtb4cVpplv1kRQ9ZEdoOM94GRo+i4IF0a3IPTtM=
    on_start: always
    on_success: always
