<?php

/**
* @file
* Contains comp_install.install.
*/

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 */
function comp_install_install() {
  // Create default taxonomny terms.
  // Gender.
  $genders = [
    'Not Identified',
    'Female',
    'Male',
  ];

  foreach ($genders as $gender) {
    Term::create([
      'vid' => 'gender',
      'name' => $gender,
    ])->save();
  }
}
