<?php

/**
* @file
* Contains comp_core.module.
*/

/**
 * Implements hook_theme().
 */
function comp_core_theme($existing, $type, $theme, $path) {
  return [
    'comp_landing' => [
      'variables' => [],
    ],
    'comp_about' => [
      'variables' => [],
    ],
    'comp_ack' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function comp_core_page_attachments(array &$attachments) {
  if (!\Drupal::currentUser()->hasPermission('access toolbar')) {
    return;
  }

  $attachments['#attached']['library'][] = 'comp_core/toolbar-overrides';
}
