<?php

use Drupal\user\Entity\User;

/**
* @file
* Contains comp_core.module.
*/

/**
 * Implements hook_theme().
 */
function comp_core_theme($existing, $type, $theme, $path) {
  return [
    'comp_landing' => [
      'variables' => [],
    ],
    'comp_about' => [
      'variables' => [],
    ],
    'comp_ack' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function comp_crud_preprocess_node__static_page(&$variables) {
  $user = \Drupal::currentUser();
  $user_roles = $user->getRoles();
  $roles_permissions = user_role_permissions($user_roles);
  kint($roles_permissions);
}
