<?php

/**
 * @file
 * Contains comp_subject_img.module.
 */

use \Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 * Creates image field for subject.
 */
function comp_subject_img_preprocess_node__subject(&$variables) {
  // Get subject id.
  $sid = $variables['node']->id();

  // Find and load parent composite.
  $results = \Drupal::entityQuery('node')
    ->condition('type', 'composite')
    ->condition('field_subjects', $sid)
    ->execute();

  // Get first result with reset() to be safe. Query should only return 1.
  $cid = reset($results);
  $composite = Node::load($cid);

  // Get composite image field.
  $comp_img = $composite->field_image->view('full');
  $variables['content']['composite_image'] = $comp_img;

}
