<?php

use Drupal\node\Entity\Node;
use Drupal\image\Entity\ImageStyle;

/**
* @file
* Contains comp_cms_extend.module.
*/

/**
 * Implements hook_form_alter().
 * Alter subject node form.
 */
function comp_cms_extend_form_alter(&$form, $form_state, $form_id) {
  // Add cropped composite preview only to ADD and EDIT subject forms.
  $scope_forms = [
    'node_subject_form',
    'node_subject_edit_form',
  ];

  // If it's a subject form.
  if (in_array($form_id, $scope_forms)) {
    // Attach JS.
    $form['#attached']['library'][] = 'comp_core/absent-on-click';

    // Retrieve subject node, id, composite id.
    $subject = $form_state->getFormObject()->getEntity();
    $sid = $subject->id();
    $preview =  FALSE;

    $cid =
      !empty($subject->get('field_composite')->getValue()[0]['target_id']) ?
      $subject->get('field_composite')->getValue()[0]['target_id'] : NULL;

    // If a composite is linked to the subject, add cropped image to form.
    if (!empty($cid)) {
      $composite = Node::load($cid);
      $comp_img = $composite->field_image;

      if (!empty($comp_img)) {
        // Retrieve display resolution (dpi).
        $dpi = intval($composite->get('field_disp_resolution')
          ->getValue()[0]['value']);

        // Load image style with preview cropping effect.
        $style_name = 'pv_composite_crop_' . $dpi . 'dpi';
        $style = ImageStyle::load($style_name);

        if (empty($style)) {
          // If preview style not available, load default image crop style.
          $style_name = $sid . '_composite_crop_' . $dpi . 'dpi';
          $style = ImageStyle::load($style_name);
        }

        if (empty($style)) {
          // If default style is also not available, load 'large' style.
          $style = ImageStyle::load('large');
        }

        if (!empty($style)) {
          // Add styled image to form.
          $styled_image_url = $style->buildUrl($composite->field_image->entity->getFileUri());
          $div_classes = 'js-form-item form-item';

          $form['subject_img'] = [
            '#type' => 'markup',
            '#prefix' => "<div id='subject-img-div' class='$div_classes'>" .
              '<label>Composite Crop Preview</label>',
            '#suffix' => '</div>',
            '#markup' => "<img id='subject-img' class='d-block' src='$styled_image_url'>",
            '#weight' => -100,
          ];
        }

        // Flush caches to trigger node preprocess on refresh.
        drupal_flush_all_caches();

        // Add composite cropping label.
        $crop_help = "Check the box below if the person is absent from the
          composite. Enter coordinates otherwise. Top coordinates correspond to
          the top-left corner where the composite should be cropped, and bottom
          correspond to the bottom-right.";

        $form['composite_cropping'] = [
          '#type' => 'markup',
          '#prefix' => "<div class='$div_classes'><p class='font-weight-bold mt-5 mb-1'>",
          '#markup' => t('Composite Crop Coordinates'),
          '#suffix' => "</p><div class='description'>$crop_help</div></div>",
          '#weight' => -10,
        ];

        // Add refresh image button.
        // Get composite image URL with a base style.
        $base_style_name = 'full_jpeg';
        $base_style = ImageStyle::load($base_style_name);
        $comp_url = $base_style->buildUrl($composite->field_image->entity->getFileUri());

        $form['refresh_subject_img'] = [
          '#type' => 'submit',
          '#value' => 'Refresh Preview',
          '#submit' => ['refresh_subject_img'],
          '#attached' => [
            'library' => [
              'comp_cms_extend/refresh_subject_img',
            ],
            'drupalSettings' => [
              'comp_cms_extend' => [
                'comp_url' => $comp_url,
              ],
            ],
          ],
          '#weight' => 4,
        ];

      }
    }

    // Set coordinate fields' states to hide them when 'absent' is checked.
    $form['composite_cropping']['#states']['invisible'][':input[name="field_absent[value]"]']
      = $form['field_top_x']['#states']['invisible'][':input[name="field_absent[value]"]']
      = $form['field_top_y']['#states']['invisible'][':input[name="field_absent[value]"]']
      = $form['field_bottom_x']['#states']['invisible'][':input[name="field_absent[value]"]']
      = $form['field_bottom_y']['#states']['invisible'][':input[name="field_absent[value]"]']
      = $form['refresh_subject_img']['#states']['invisible'][':input[name="field_absent[value]"]']
      = ['checked' => TRUE];
  }
}

// Refresh subject image preview.
function refresh_subject_img($form, &$form_state) {

  // Retrieve subject node, id, composite id.
  $subject = $form_state->getFormObject()->getEntity();
  $sid = $subject->id();

  $cid =
    !empty($subject->get('field_composite')->getValue()[0]['target_id']) ?
    $subject->get('field_composite')->getValue()[0]['target_id'] : NULL;

  // If a composite is linked to the subject, add cropped image to form.
  if (!empty($cid)) {
    $composite = Node::load($cid);
    $comp_img = $composite->field_image;

    if (!empty($comp_img)) {
      // Retrieve display resolution (dpi).
      $dpi = intval($composite->get('field_disp_resolution')
        ->getValue()[0]['value']);

      // Crop effect configuration.
      // Retrieve coordinates from subject record.
      $topX = floatval($form_state->getValue('field_top_x')[0]['value']);
      $topY = floatval($form_state->getValue('field_top_y')[0]['value']);
      $botX = floatval($form_state->getValue('field_bottom_x')[0]['value']);
      $botY = floatval($form_state->getValue('field_bottom_y')[0]['value']);

      // Create preview style.
      update_crop_style('pv', $topX, $topY, $botX, $botY, $dpi, TRUE);

      $form_state->setRebuild(TRUE);
    }
  }
}
