features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 0
  path: ''
b4_top_container: container
b4_body_schema: none
b4_body_bg_schema: none
b4_navbar_schema: dark
b4_navbar_bg_schema: dark
b4_footer_schema: none
b4_footer_bg_schema: none
